### ISSUE TITLE
Fail to decode request due to: RpcInvocation

### ISSUE THREAD

**Issue by yangchongduo** [p412726700/node-zookeeper-dubbo#105]
```
const customerObj = {
      $class: 'com.GetSellingCountParam',
      $: {
        beginStockDate: java.String(1557304977000),
        endStockDate: java.String(1557304977000),
        shopkeeperId: java.String('2323')
      }
    }
```
一直报这个错 不知道为什么

**Comment by yangchongduo** [comment]
Do not add a version number
dubboVer is not required
Can the document be written?

**Comment by zjfcgis** [comment]
我的也是这个问题，在网上找到了解决方案，不过需要改这个库的源码，坑啊。

> ```
> const customerObj = {
>       $class: 'com.GetSellingCountParam',
>       $: {
>         beginStockDate: java.String(1557304977000),
>         endStockDate: java.String(1557304977000),
>         shopkeeperId: java.String('2323')
>       }
>     }
> ```
> 
> 一直报这个错 不知道为什么

**Comment by zjfcgis** [comment]
应该是js的数据类型和后端dubbo参数对应不上，需要检查数据类型并严格对应，比如数字只能是2而不是"2"。
