### ISSUE TITLE
新人提问：请问和 dubbo-js 有什么区别

### ISSUE THREAD

**Issue by youthlin** [p412726700/node-zookeeper-dubbo#107]
[dubbo-js](https://github.com/apache/dubbo-js) <- 看起来还比较官方

这两个好像都可以实现 Node 和 Java 通过 Dubbo 通信。
不知道该选哪个，大家有什么建议嘛？

**Comment by godkun** [comment]
不用考虑，用 dubbo-js 。
腾讯、拼多多、千米、vivo 等大厂都在用。稳定性完全可以保障
