### ISSUE TITLE
判断为空的问题

### ISSUE THREAD

**Issue by master-xie** [p412726700/node-zookeeper-dubbo#16]
if (heap[15] === 3 && heap.length < 20) { // 判断是否没有返回值
不能捕获到为空的情况

**Comment by p412726700** [comment]
捕获不到为空是怎么说 java返回的是null?

**Comment by master-xie** [comment]
他没有返回值，方法返回void，这种情况得到的<Buffer da bb 02 14 00 00 00 00 00 00 00 00 00 00 00 01 92>

**Comment by master-xie** [comment]
他没有返回值，方法定义返回void ：
buffer为： da bb 02 14 00 00 00 00 00 00 00 00 00 00 00 01 92

**Comment by p412726700** [comment]
试下2.1.0版本的行不

**Comment by master-xie** [comment]
可以的!
