### ISSUE TITLE
err处理问题

### ISSUE THREAD

**Issue by master-xie** [p412726700/node-zookeeper-dubbo#18]
client.on('error', function (err) {
      self._execute(method, args, host);
 });
如果服务端口变了，就会触发error，这样写就会一直错下去，不会有返回值，是不是去重新获取一下zk上注册的provider，然后再试一次，不行抛异常呢？

**Comment by p412726700** [comment]
可以 我们考虑下 未来的版本会加上

**Comment by master-xie** [comment]
好的

**Comment by p412726700** [comment]
@master-xie 你们这边改端口也是会通知到zk的 对吧

**Comment by master-xie** [comment]
是的，zk随时都是最新的

**Comment by p412726700** [comment]
试下新版本的

**Comment by master-xie** [comment]
嗯 昨天试过了 赞！
