### ISSUE TITLE
请问支持2.8版本的dubbo么

### ISSUE THREAD

**Issue by maxjunjun** [p412726700/node-zookeeper-dubbo#19]
支持2.8版本的dubbo么

**Comment by p412726700** [comment]
目前所有的功能都是基于2.6的 如果要用的话 建议先测试下是否能跑通

**Comment by caomu** [comment]
2.8的dubbo？指的是不是dubbox？

**Comment by maxjunjun** [comment]
应该是dubbox

**Comment by caomu** [comment]
dubbox默认用的序列化方法是json，走http协议。nodejs调用dubbox超级方便！用不着我们写的这个库的，我们写的这个库目的是为了调用那些用dubbo协议对外暴露接口的系统

**Comment by maxjunjun** [comment]
但是提供者注册时设置的是dubbo协议，也可以么。

**Comment by caomu** [comment]
试试看，理论上是可以的。我们没环境，试不了
