### ISSUE TITLE
2.0版本里NZD是一个类

### ISSUE THREAD

**Issue by lianer** [p412726700/node-zookeeper-dubbo#22]
```js
const Dubbo=nzd(opt);
```
readme里写的是方法调用，其实是一个类

**Comment by p412726700** [comment]
多谢指正 ：） 冒昧问下 你们厂也在用nodejs么

**Comment by lianer** [comment]
通过您的工具，成功调通了dubbo，真是感谢。
我现在是尝试阶段，用nodejs做一些不太重要的功能，现在就想做个加班报名的系统，用现有的dubbo提供的账号认证服务，还没有正式应用在业务上做后端服务。

**Comment by p412726700** [comment]
恩恩 明白 你的一小步公司的一大步
