### ISSUE TITLE
跑demo遇到的问题

### ISSUE THREAD

**Issue by sunnyboy3** [p412726700/node-zookeeper-dubbo#24]
你好，
const customerObj = {
          $class: 'vmacro.surface.UserService',
          $: {
              a: 1,
              b: 'selectByPrimaryKey', //**这个是方法名吗**
              c: {$class: 'java.lang.Long', $: 1}
          }
      };
这里是配置一个类的所有属性？？？
        console.log(Dubbo)
      Dubbo.User
          .selectByPrimaryKey({'$class': 'java.lang.Long', '$': '10000000'},customerObj)
          .then(console.log(customerObj))
          .catch(console.error)
这一块应该怎么配置User.selectByPrimaryKey始终报错不是函数

**Comment by shi2713** [comment]
同问

**Comment by p412726700** [comment]
const Dubbo=new nzd(opt); 
有个初始化的过程，初始化完毕后会在控制台打印 **Dubbo service init done** 这时才能执行方法

**Comment by shi2713** [comment]
未初始完显示：Cannot read property 'getCompareInfo' of undefined
初始完显示：Dubbo.Foo.getCompareInfo is not a function

 
![xx1](https://cloud.githubusercontent.com/assets/9816437/19751217/4541b68c-9c2a-11e6-89e5-3ac4e9a2197d.jpg)

**Comment by p412726700** [comment]
把 ```cons Dubbo=new nzd(opt)``` 放在app.js中，其它放在路由里面，我们这边Dubbo是挂在global下的也就是 ```global.Dubbo=Dubbo```

**Comment by shi2713** [comment]
可以初始化了，可还是会报Dubbo.Foo.getCompareInfo is not a function

**Comment by LargeRui** [comment]
TypeError: Cannot read property 'charAt' of undefined  这个报错是怎么回事?调用的参数类型不对吗?

**Comment by p412726700** [comment]
@LargeRui 大多情况下都是因为参数错误导致
