### ISSUE TITLE
关于负载均衡配置

### ISSUE THREAD

**Issue by sunnyboy3** [p412726700/node-zookeeper-dubbo#25]
我调试通了，但是始终负载均衡没有办法调试通，

**Comment by p412726700** [comment]
所说的负载均衡意思是不同的请求会连接到不同的provider么？这样的话，建议用2.0版本的

**Comment by sunnyboy3** [comment]
恩恩，是的，

**Comment by sunnyboy3** [comment]
2.0版本是支持的是吧，那，还有一个问题：
const customerObj = {
  $class: 'com.xxx.XXXDTO',
  $: {
    a: 1,
    b: 'test',
    c: {$class: 'java.lang.Long', $: 123}
  }
};

Dubbo.Foo
  .xxMethod({'$class': 'java.lang.Long', '$': '10000000'},customerObj)
  .then(console.log)
  .catch(console.error)
这个地方没有看明白

**Comment by p412726700** [comment]
这里就是方法请求咯

**Comment by shi2713** [comment]
这块我也没太看明白  xxMethod是方法名理解，后面(xx,,customerObj)    xx是参数？customerObj是参数？
调试时报：
Dubbo.Foo.getCompareInfo is not a function
