### ISSUE TITLE
Fail to decode request due to: RpcInvocation

### ISSUE THREAD

**Issue by yyxiong** [p412726700/node-zookeeper-dubbo#28]
找到错误提示的原因说可能是：
1.传输的参数没有实现序列化接口(包括内部的对象属性)；
2.传输的参数中是否包含了不能序列化的属性，例如ImmutableList、Joda DateTime

而传参数对象为
```json
{ '$class': 'com.user.dto.LoginUser',
  '$':
   { id: '100018577',
     mainId: 100018577,
     account: null,
     email: 'test7@test.com',
     mobile: '51807',
     posts: [ '经办岗' ],
     activate: true,
     shopId: null,
     roles: [],
     name: '经办岗'} }
```
调用代码为
```js
Dubbo.UserReadService
    .getUserInfo({'$class': 'com.user.dto.LoginUser', '$':user})
```

**Comment by p412726700** [comment]
用的哪个版本？

**Comment by yyxiong** [comment]
node-zookeeper-dubbo版本为2.1.4
java的dubbo版本为2.5.1

**Comment by harryhan1989** [comment]
解决了么？

**Comment by harryhan1989** [comment]
项目需求nodejs连接dubbo接口，找到node-zookeeper-dubbo很不错，但是复杂java对象却很难开发。网上也没搜到这方面的工具，索性自己写了个，经过多次调试试错，实现了普通json自动转换为dubbo可识别的java序列化对象，可支持java实体类内嵌实体类及内嵌List这种转化，简单高效，现在实现的比较简单，就是个工具类，有兴趣的同学欢迎包装为nodejs通用插件或eggjs插件：https://github.com/harryhan1989/json-to-java

**Comment by harryhan1989** [comment]
你这个是没有遍历对象里面的键值做转换
