### ISSUE TITLE
dependencies中多个interface问题

### ISSUE THREAD

**Issue by sunnyboy3** [p412726700/node-zookeeper-dubbo#29]
我最近遇到一个问题，希望大神给我指点一二：
dependencies:{
                Role: {interface: 'vmacro.surface.RoleService', version: '1.0.0', timeout: 6000},
                User:{interface:'vmacro.surface.UserService',version:'1.0.0',timeout:6000}
 }
我这样的时候会报错：Reg consumer failed ：Exception ：NO_NODE[-101]
如果这样的话
dependencies:{
                Role: {interface: 'vmacro.surface.RoleService', version: '1.0.0', timeout: 6000}
 }
就不会报错这个是怎么回事儿呀，老版本，比较急呀，麻烦了

**Comment by p412726700** [comment]
用的是哪个版本？

**Comment by sunnyboy3** [comment]
版本2.1.4这个版本我感觉不对，应该是老版本的
就是使用这种方式获取数据这个版本
await http.Du.User.selectByExample({'$class': 'java.lang.String', '$': offset})
            .then(
                function (data) {
                    return http.json(data)
                }
            ).catch(console.error);

**Comment by sunnyboy3** [comment]
我跟踪到应该是在register.js中的
self.client.create(path, CREATE_MODES.EPHEMERAL, function (err, node) {
          if (err) {
            console.log('sadasdfasdf');
            console.error('Reg consumer failed:' + err.stack);
          }
        });
这一句话报错来的错误
