### ISSUE TITLE
Reg consumer failed

### ISSUE THREAD

**Issue by KELEN** [p412726700/node-zookeeper-dubbo#36]
请问这个是什么错误！

**Comment by p412726700** [comment]
这个是注册节点信息失败
你这边启动完成后 能正常调用么？

**Comment by penweizgx** [comment]
现在可以了


原始邮件
发件人:OmniPnotifications@github.com
收件人:p412726700/node-zookeeper-dubbonode-zookeeper-dubbo@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2017年3月19日(周日) 20:36
主题:Re: [p412726700/node-zookeeper-dubbo] Reg consumer failed (#36)


这个是注册节点信息失败
 你这边启动完成后 能正常调用么？

**Comment by jizhuofeng** [comment]
遇到类似的问题
 Reg consumer failed:NO_NODE: Exception: NO_NODE[-101]，
每次JAVA端提供好了接口，然后node端把接口配置进去然后调用时，就报这个错误。
看了一下此时zookeeper上没有consumers目录，当java使用了该接口之后，zookeeper上出现了consumers目录， 然后node端就可以使用该接口了。

每次java端提供新的接口时都会出现这种情况
