### ISSUE TITLE
总是报TypeError: Dubbo.Foo.say is not a function

### ISSUE THREAD

**Issue by 156554395** [p412726700/node-zookeeper-dubbo#38]
const customerObj = {
  $class: 'com.xxx.XXXDTO',
  $: {
    a: 1,
    b: 'test',
    c: {$class: 'java.lang.Long', $: 123}
  }
};
这个对象里面的参数是什么？
已有初始化完毕标志：Dubbo service init done
总是报TypeError: Dubbo.Foo.say is not a function

**Comment by p412726700** [comment]
你怎么用的 详细用法贴出来看看

**Comment by 156554395** [comment]
已经调好了！谢谢！

**Comment by p412726700** [comment]
好的 觉得还行的话 麻烦点个赞 哈哈哈
