### ISSUE TITLE
Error: string is not valid UTF-8 encode

### ISSUE THREAD

**Issue by quanfuli** [p412726700/node-zookeeper-dubbo#4]
成功调用后台的方法，返值为String类型,可是前端返回下面的错误，是什么原因呢
我找到\hessian.js\lib\utils.js文件中找到
```
exports.lengthOfUTF8 = function (head) {
	debugger;
  if (head < 0x80) {
    return 1;
  }
  if ((head & 0xe0) === 0xc0) {
    return 2;
  }

  if ((head & 0xf0) === 0xe0) {
    return 3;
  }
  throw new Error('string is not valid UTF-8 encode');
};
```

**Comment by p412726700** [comment]
其它类型的有报错么？可否稍微详细一点，比如字符串值是什么？

**Comment by quanfuli** [comment]
字符串类型为：{"id":1,"name":"SAN FRANCISCO","state":"CA","country":"US"}
如果是整形的话报错：TypeError: Cannot read property 'toString' of undefined
代码如下：
var Service=require('node-zookeeper-dubbo');
var opt={
  env:'1.0.0',
  conn:'127.0.0.1:2181',
  path:'com.abc.common.DemoService'
}

var method = 'returnHello';
var arg1={$class:'int',$:1}
var args=[arg1];

var service = new Service(opt);
service.excute(method,args,function(err,data){
  if(err){
    console.log("error:"+err);
    return;
  }
  console.log("data:"+data);
});

public String returnHello(int id) {
		try {
			City city = (City) dao.findForObject("CityMapper.selectCityById",
					id);
			String result = StringUtil.toJson(city);
			System.out.println(result);
			return result;
		} catch (Exception e) {
			e.printStackTrace();
		}
		return "hello world";
	}

**Comment by p412726700** [comment]
刚才把你提供的字符串作为返回我这边是能调通的，“如果是整形的话报错” 这是什么意思？

**Comment by quanfuli** [comment]
如果返回值是字符串报string is not valid UTF-8 encode错误。
--------------------如public String returnHello(int id)

如果返回值是整形报TypeError: Cannot read property 'toString' of undefined
-------------------如public int returnHello(int id)

**Comment by p412726700** [comment]
@quanfuli 不应该啊 我们这边
```
public String foo(){
    return 'Hello World'
}
```
都能正常返回的，你修改下nodejs这边的opt为
```
opt={
  env:'TEST', // 根据你zookeeper的环境
  conn:'127.0.0.1:2181',
  path:'com.abc.common.DemoService',
  version:'1.0.0' //dubbo版本
}
``` 
试试看

**Comment by quanfuli** [comment]
我不是很了解     “env:'TEST'// 根据你zookeeper的环境 ” 
我看了一下代码
  this._attchments = {
    $class: 'java.util.HashMap',
    $     : {
      path     : this._path,
      interface: this._path,
      version  : this._env,
      timeout  : '60000'
    }
  };
  this.zk          = new ZK(opt.conn, this._env);
};
我没理解错的话。是@Service(version = "1.0.0")中的版本。既然你那没错。我想可能是我dubbo配置的问题。我继续研究

**Comment by quanfuli** [comment]
我更新了最新的版本没有问题了。

**Comment by quanfuli** [comment]
更新了最新版本，可以运行了。是因为什么原因。

**Comment by p412726700** [comment]
@quanfuli  恩 修改了一下代码逻辑 没问题我关issue了啊

**Comment by quanfuli** [comment]
@p412726700 Ok,非常感谢！
