### ISSUE TITLE
Dubbo service init done的颜色能否可选？

### ISSUE THREAD

**Issue by h1orz** [p412726700/node-zookeeper-dubbo#41]
有些平台读取日志时，颜色编码会引起乱码，比如我们...😄

**Comment by p412726700** [comment]
呃... 可能近期没时间调整 这个对你们影响大么？

**Comment by h1orz** [comment]
日志系统不支持Linux颜色编码，forever和log4js我都配置成没颜色的了。
那我先临时放本地去掉颜色用一下，希望后续的版本会更新。😄
Thx.

**Comment by p412726700** [comment]
好的 感谢反馈 😄
