### ISSUE TITLE
增加下面代码即可支持dubbox(2.8.X）

### ISSUE THREAD

**Issue by aierpdotorg** [p412726700/node-zookeeper-dubbo#42]
/libs/encode.js 

35行增加下面代码：
 var ver = this._opt._dver || '2.5.3.6';
  if(ver.split('.')[0] >= '2' && ver.split('.')[1] >= '8'){
    body.write(-1);
  }

**Comment by p412726700** [comment]
厉害，你可以提交一个pr，不过请务必充分测试，🙏

**Comment by lishengguo** [comment]
我提交了PR #43 ，请帮忙处理，谢谢啦

**Comment by hoefershen** [comment]
这边是使用dubboX  2.8.4 版本，默认dubbo协议，但一直不行，

const nzd=require('node-zookeeper-dubbo');
 

const opt={
  application:{name:'anyproxy'},
  register:'127.0.0.1:2181',
  dubboVer:'2.8.4',
  root:'dubbo',
  dependencies:{
    IAPP:{
      interface:'com.xxx.IAppService',
      version:'2.8.4',
      timeout:30000
      }
    }
  }  


opt.java = require('js-to-java')
const Dubbo=new nzd(opt);


Dubbo.IAPP.dubboDemo({'$class': 'java.lang.String', '$': 'dddds'})


----------
报错如下：
Dubbo.IAPP.dubboDemo({'$class': 'java.lang.String', '$': 'dddds'})
          ^

TypeError: Cannot read property 'dubboDemo' of undefined
    at Object.<anonymous>  
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3

实际上这个dubboDemo方法在Dubbo admin是可以找到，并被其他应用调用的。
已经确定本地的NZD是最新的，有最新的PR。
麻烦帮忙看下啥原因？试了好多种Demo的写法，都 是有问题

**Comment by hoefershen** [comment]
const nzd=require('node-zookeeper-dubbo');
const app=require('express')();
const opt={
  application:{name:'IAppService'},
  register:'127.0.1.1:2181',
  dubboVer:'2.8.4',
  root:'dubbo',
  dependencies:{
    Foo:{
      interface:'com.xxx.IAppService',
      version:'2.8.4',
      timeout:6000,
      group:'item'
	  methodSignature: {       
         findById = (id) => [ {'$class': 'java.lang.Long', '$': id} ],
      }
    }
   
  }  
}
opt.java = require('js-to-java')

const Dubbo=new nzd(opt);


app.get('/foo/dubboDemo',(req,res)=>{
  Dubbo.Foo
    .getByName('ddd')
    .then(data=>res.send(data))
    .catch(err=>res.send(err))
})

app.get('/foo/findById',(req,res)=>{
  Dubbo.Foo
    .findById(101)
    .then(data=>res.send(data))
    .catch(err=>res.send(err))
})



app.listen(9090)


-----------------
         methodSignature: {
         ^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
   at createScript (vm.js:53:10)
   at Object.runInThisContext (vm.js:95:10)
   at Module._compile (module.js:543:28)
   at Object.Module._extensions..js (module.js:580:10)
   at Module.load (module.js:488:32)
   at tryModuleLoad (module.js:447:12)
   at Function.Module._load (module.js:439:3)
   at Module.runMain (module.js:605:10)
   at run (bootstrap_node.js:427:7)
   at startup (bootstrap_node.js:151:9)
-----------------
这是另外一种 调用DubboX时的写法，就报上面的错误，不知道是不是同一个问题。。。

**Comment by lishengguo** [comment]
group:'item'  后面缺了逗号

**Comment by lishengguo** [comment]
const Dubbo=new nzd(opt);
//要等Dubbo连接zookeeper成功了，才会创建IAPP对象。
Dubbo.IAPP.dubboDemo({'$class': 'java.lang.String', '$': 'dddds'})

**Comment by hoefershen** [comment]
问题解决了，原来是NODEJS版本问题，使用v7.10.0有问题，换成node-v6.11.2-x64 就可以了。。谢谢。

**Comment by hoefershen** [comment]
TypeError: Cannot read property 'dubboDemo' of undefined这个问题更换node版本解决了，
有显示Dubbo service init done，但还有如下问题。

> Fail to decode request due to: RpcInvocation [methodName=dubboDemo, parameterTypes=[], arguments=null, attachments={dubbo=2.8.4, input=228, path=com.xxx.IAppService, version=null}

请求/foo/dubboDemo  报以上错误，使用JAVA调用该方法时，是没有问题的。

服务提供方则报显示如下信息

>2017-08-25 11:24:10 [New I/O worker ] WARN  com.alibaba.dubbo.rpc.protocol.dubbo.DecodeableRpcInvocation - [DUBBO] Decode rpc invocation failed: expected map/object at java.lang.String (Ljava/lang/String;), dubbo version: 2.8.4, current host: 127.0.0.1
com.alibaba.com.caucho.hessian.io.HessianProtocolException: expected map/object at java.lang.String (Ljava/lang/String;)
	at com.alibaba.com.caucho.hessian.io.AbstractDeserializer.error(AbstractDeserializer.java:108)
	at com.alibaba.com.caucho.hessian.io.AbstractMapDeserializer.readObject(AbstractMapDeserializer.java:70)

**Comment by lishengguo** [comment]
如果给methodSignature赋值了，那么把 Dubbo.IAPP.dubboDemo({'$class': 'java.lang.String', '$': 'dddds'})
改成
Dubbo.IAPP.dubboDemo('dddds')

**Comment by hoefershen** [comment]
>methodSignature: {
^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
at createScript (vm.js:53:10)
at Object.runInThisContext (vm.js:95:10)
at Module._compile (module.js:543:28)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)

这个问题还是存在的，一直赋值不了，暂不知道啥原因。

下面这个是啥原因，能分析下吗？
Fail to decode request due to: RpcInvocation

**Comment by lishengguo** [comment]
group:'item' 后面缺了逗号

**Comment by hoefershen** [comment]
逗号问题，已经更正了。主要怀疑是数据类型问题，String传过去，dubbo服务方没有找到对应的方法来解析。

**Comment by hoefershen** [comment]
目前我的DubboX 使用hessian2 hessian2 protocol for serialization and deserialization.  不知道这是否有影响？

**Comment by chua1989** [comment]
我也是有Fail to decode request due to: RpcInvocation这个问题，即使函数是不需要参数的调用也会这样

**Comment by p412726700** [comment]
@lishengguo  兄弟 因为我们这没用2.8.4所以暂时给不了较为合理的解决方案 你这边有什么建议么
