### ISSUE TITLE
调取服务怎么传递枚举类型

### ISSUE THREAD

**Issue by mideaEEGroup** [p412726700/node-zookeeper-dubbo#45]
![image](https://user-images.githubusercontent.com/30041172/28612442-dcb1a450-7221-11e7-989b-3e363757f0d3.png)

这个是我传递的参数， 其中orderStatus是一个枚举参数

我这样子传递orderStatus，就报错了，
![image](https://user-images.githubusercontent.com/30041172/28612409-c9eb9f10-7221-11e7-9a31-0615d8359ee2.png)

怎么chu传递枚举类型？求支持

**Comment by p412726700** [comment]
枚举用这个 java.util.Enumeration

**Comment by mideaEEGroup** [comment]
不行哈，这个枚举类型是复合型的
