### ISSUE TITLE
Reg consumer failed:NO_NODE: Exception: NO_NODE[-101]

### ISSUE THREAD

**Issue by jizhuofeng** [p412726700/node-zookeeper-dubbo#46]
现象： 
每次JAVA端提供好了接口，然后node端把接口配置进去然后调用时，就报这个错误。
看了一下此时zookeeper上没有consumers目录，当java使用了该接口之后，zookeeper上出现了consumers目录， 然后node端就可以使用该接口了。

每次java端提供新的接口时都会出现这种情况

**Comment by p412726700** [comment]
是的 因为需要把消费者注册到zk中 java端的做法是在zk中创建consumers目录如果没有的话 目前这个库只注册节点信息也就是只创建节点 不创建目录的 一般来说 只要dubbo服务不停的话consumers目录是不会被删除的

**Comment by jizhuofeng** [comment]
但是如果java提供的新接口只提供给node用的话， consumers目录一直不会被创建呀， 需要手工创建consumers目录。
刚看了一下代码， 在注册客户端节点的时候判断一下consumers目录是否存在， 存在则创建节点，不存在创建cunsumers之后再创建节点。就可以解决了吧。

**Comment by p412726700** [comment]
是的 理论上这样是可行的 你这边如果比较紧急的话 可以提个PR 因为我们最近比较忙 所以可能 😂

**Comment by jizhuofeng** [comment]
目前还好， 然后可以手工先创建consumers目录！ 还有一点就是和provider的连接问题， 每次调用方法都重建连接， 是不是也可以优化一下连接方式！

**Comment by jizhuofeng** [comment]
刚提了一个pr, 帮忙审核一下！
