### ISSUE TITLE
请问枚举类型这个值应该怎么传递（是复合型枚举哈，不是简单的枚举）

### ISSUE THREAD

**Issue by mideaEEGroup** [p412726700/node-zookeeper-dubbo#48]
![image](https://user-images.githubusercontent.com/30041172/28612442-dcb1a450-7221-11e7-989b-3e363757f0d3.png)

这个是我传递的参数， 其中orderStatus是一个枚举参数

我这样子传递orderStatus，就报错了，
![image](https://user-images.githubusercontent.com/30041172/28612409-c9eb9f10-7221-11e7-9a31-0615d8359ee2.png)

怎么传递枚举类型？求支持
后台的java代码这个类型是这样的：
![image](https://user-images.githubusercontent.com/30041172/29305781-0472f8b2-81cd-11e7-8553-0d74abcc292f.png)
![image](https://user-images.githubusercontent.com/30041172/29305790-0e71ef94-81cd-11e7-9a9c-3cce5001f22f.png)

**Comment by p412726700** [comment]
把28换成 {name: 'WAIT_BUYER_CONFIRM_GOODS'} 试试

**Comment by p412726700** [comment]
@mideaEEGroup  可以了吗？

**Comment by mideaEEGroup** [comment]
可以啦

**Comment by p412726700** [comment]
OK
