### ISSUE TITLE
关于服务连接状态处理的问题

### ISSUE THREAD

**Issue by bytesnail** [p412726700/node-zookeeper-dubbo#52]
基于Promise/A+和简单的消息机制改写了一下，提供了获取一个或多个接口连接状态的方法；
毕竟是基于nodejs的基础模块，还是希望能够有一个异步回调，能够准确地知道服务是否可用；
改写的代码地址：https://github.com/bytesnail/node-zookeeper-dubbo/blob/optimize/index.js

**Comment by p412726700** [comment]
感谢关注本项目及提供新特性，🙏，不过有点不太明白，准确知道服务是否可用的话，只能是通过发起一次请求才能知道，如果服务不可用的话，会返回特定的错误信息，可以用Promise.catch捕获到。
其次，代码好像是构造了一个事件系统，为什么不用node自带的Events模块呢。
最后，添加的新特性如何使用貌似没有说明，能否在READEME里面添加上使用说明。
