### ISSUE TITLE
对象内部还有对象的情况会报序列化错误

### ISSUE THREAD

**Issue by chua1989** [p412726700/node-zookeeper-dubbo#54]
比如
比如

{
  "$class":"com.xxx.RandomAmountBindingApplyDto",
  "$":{
      "userName":"张三",
      "customerType":{
          "$class":"com.xxx.CustomerType",
          "$":{
              "code":"0",
              "chineseName":"个人"
           }
      }
  }
}
里面的有一个customerType属性也是一个对象
会报：ail to decode request due to: RpcInvocation

**Comment by harryhan1989** [comment]
项目需求nodejs连接dubbo接口，找到node-zookeeper-dubbo很不错，但是复杂java对象却很难开发。网上也没搜到这方面的工具，索性自己写了个，经过多次调试试错，实现了普通json自动转换为dubbo可识别的java序列化对象，可支持java实体类内嵌实体类及内嵌List<Model>这种转化，简单高效，现在实现的比较简单，就是个工具类，有兴趣的同学欢迎包装为nodejs通用插件或eggjs插件：[https://github.com/harryhan1989/json-to-java](https://github.com/harryhan1989/json-to-java )

**Comment by harryhan1989** [comment]
我项目比较复杂，很多这种对象内嵌对象，甚至是内嵌对象的内嵌对象，所以封装了个json to java的方法
