### ISSUE TITLE
node-zookeeper-dubbo服务启动报错

### ISSUE THREAD

**Issue by 151608133** [p412726700/node-zookeeper-dubbo#57]
各位大牛，新入手node ,求指导！
代码如下 ：
var opt = {
    application: { name: 'df' },
    register: '28.163.1.188:2181',
    root: 'dubbo',
    dependencies: {
        WcnService: {
            interface: 'com.foundersc.crm.mobile.service.AppointRemoteService',
            version: '1.0.1',
            timeout: 6000,
            group: 'test',
            methodSignature: {
                getbrokerAccountCnt = (userId) => (java) => [java.String(userId)],
            }
        }
    }
};

启动时报错：

E:\Fouder\nodeWorkspace\node_ws_demo\bin\www:49
                getbrokerAccountCnt = (userId) => (java) => [java.String(userId)],
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid shorthand property initializer
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
不知道是哪个地方配错了 ，我参考网上的模板来写的 。麻烦大牛来指导下。十分感谢！

**Comment by p412726700** [comment]
node版本是？

**Comment by 151608133** [comment]
node的版本是8.9.1  代码我用图片放上来吧  。也刚开始用githup 不太熟悉  ，望谅解！

![default](https://user-images.githubusercontent.com/21124892/33163957-c3469216-d06b-11e7-943e-0cbd1d197bc6.png)

**Comment by p412726700** [comment]
dubboVer 这个参数貌似没生命

**Comment by p412726700** [comment]
另外把 getbroerAccount = 改成 getbroerAccount :

**Comment by 151608133** [comment]
加上了  还是这样。我比较了下 ，也没有什么缺的东西了 。
![default](https://user-images.githubusercontent.com/21124892/33164535-34be84e2-d06e-11e7-96c6-811206d156fe.png)

**Comment by p412726700** [comment]
把50行的 getbroerAccount = 改成 getbroerAccount :

**Comment by 151608133** [comment]
多谢了！服务启动正常了！
我是参照这个文档写的（https://www.npmjs.com/package/node-zookeeper-dubbo），文档可能有点问题：
![default](https://user-images.githubusercontent.com/21124892/33164773-3e0cf00a-d06f-11e7-8967-2370b48de866.png)

**Comment by 151608133** [comment]
对node 的语法有点不理解 ，直接一直搞java  这一块都看不明白为什么要这么写 。

**Comment by p412726700** [comment]
恩 回头我把npm更新下

**Comment by 151608133** [comment]
十分感谢！！

**Comment by 151608133** [comment]
调用的时候报这个，那个函数不是已经有定义了么 ？ 
![default](https://user-images.githubusercontent.com/21124892/33165421-b6bed638-d071-11e7-8a0e-21b0b80011df.png)

**Comment by 151608133** [comment]
这个是什么问题 ？能帮忙解决么？ 谢谢！周边实在是没有熟悉node的人 ，麻烦提醒下！

**Comment by p412726700** [comment]
应该是初始化没完成就开始调用了

**Comment by 151608133** [comment]
这个是由于zookeeper里没有暴露的接口数据么 ？

**Comment by 151608133** [comment]
![default](https://user-images.githubusercontent.com/21124892/33544540-1f98095c-d916-11e7-9000-9d801e44b317.png)

**Comment by 151608133** [comment]
昨天的问题解决了 ，是由于别人给的注册中心地址不对 。现在换了注册中心地址 ，但是ip和端口地址都对了，我看得到注册中心里有接口数据，但是还是报错了 。不知道是什么原因。
下面这个是 错误信息:
![default](https://user-images.githubusercontent.com/21124892/33585856-7578b57a-d9a1-11e7-9509-882096fbc068.png)
下面这个是注册中心的数据信息：
![default](https://user-images.githubusercontent.com/21124892/33585883-91f419ce-d9a1-11e7-8973-6a9cccb57f64.png)
下面是代码：
![default](https://user-images.githubusercontent.com/21124892/33585903-a88ecf30-d9a1-11e7-842a-481229da2ceb.png)
麻烦帮忙指导下，谢谢！

**Comment by 151608133** [comment]
![default](https://user-images.githubusercontent.com/21124892/33591365-2e0470ca-d9c0-11e7-8262-3bc2ebd102cb.png)
我连接的时候报这个 ，是不是由于zookeeper 限制了最多连接数 ？ 但是我看了zookeeper 的配置 ，maxClientCnxns这个参数没有配置，默认应该是不限制吧 ？
