### ISSUE TITLE
NO_NODE: Exception: NO_NODE[-101]

### ISSUE THREAD

**Issue by lichenabson** [p412726700/node-zookeeper-dubbo#67]
链接dubbo时一直报
{ NO_NODE: Exception: NO_NODE[-101]
    at ConnectionManager.onSocketData (D:\workspace2\dubbo-node-zookeeper\node_modules\_node-zookeeper-client@0.2.2@node-zookeeper-client\lib\ConnectionM
anager.js:570:35)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
  code: -101,
  name: 'NO_NODE',
  path: undefined,
  message: 'Exception: NO_NODE[-101]' }这个错，
是什么问题导致的呢

**Comment by p412726700** [comment]
@lichenabson  配置文件怎么写的

**Comment by lichenabson** [comment]
@p412726700  是指这个吗
const nzd=require('node-zookeeper-dubbo');
const app=require('express')();
const opt={
    application:{name:'Provider'},
    register:'192.168.1.119:2181',
    dubboVer:'2.5.3',
    root:'dubbo',
    dependencies:{
        provider:{
            interface:'com.alibaba.dubbo.demo.impl.Provider',
            version:'LATEST',
            timeout:6000,
            group:'isis',
            methodSignature: {
                getPermissions : (id) => [ {'$class': 'java.lang.Long', '$': id} ],
            }
        }
    }
}

**Comment by p412726700** [comment]
应该是在zk上找不到com.alibaba.dubbo.demo.impl.Provider这个服务，你java能正常调用么？

**Comment by lichenabson** [comment]
java可以的

**Comment by lichenabson** [comment]
如果照你的说的zk上找不到服务的话，那我再进一步定义下问题

**Comment by lichenabson** [comment]
@p412726700 已经解决了，定义服务的时候，需要将version与group也一一对应上

**Comment by xiaojinhe2** [comment]
@lichenabson 我也遇到你说的问题了，请问你说的“定义服务的时候，需要将version与group也一一对应上”是说的在使用java定义方法的时候，需要在配置文件中指定详细的version和group吗，然后在nodejs中使用对应的version和group，是说的这个意思吗？
