### ISSUE TITLE
如果，第一个参数没有，应该传什么值？

### ISSUE THREAD

**Issue by git-lt** [p412726700/node-zookeeper-dubbo#7]
接口第一个参数没有，node这边应该传值给java？

**Comment by p412726700** [comment]
没有参数就传空数组

**Comment by p412726700** [comment]
第一个参数在java那边是什么类型的呢

**Comment by git-lt** [comment]
Integer index, Integer length, Byte status, Byte tag

**Comment by git-lt** [comment]
index.js 195行 是什么意思 (heap.length >= bl) && client.destroy();
我的程序总是在这里为true, 连接就关闭了

**Comment by git-lt** [comment]
@p412726700 方便提供一下你们服务端service的服务配置吗？

**Comment by caomu** [comment]
integer为空的话，试试看传null
