### ISSUE TITLE
请教一下，使用node-zookeeper-dubbo可以连接java 成功，同时方法也可以执行成功，但是无法取出结果是什么情况？

### ISSUE THREAD

**Issue by Erchoc** [p412726700/node-zookeeper-dubbo#70]

**Comment by Erchoc** [comment]
之前使用express框架使用，然后可以跑通，而且结果也可以取出，
然后现在使用模块，
"moleculer": "^0.12.0",
"moleculer-web": "^0.6.4",
没有用express模块。结果是可以与java连通，java端也可以看到调用成功，但是node端无法获取返回结果？？？好像是回调有问题。以下是几种回调方式。希望获得你的帮助，谢谢。

`			handler(ctx) {
        console.log("data");
        Dubbo.IUserService.
          getUser(1,function (err,data) {
          if(err){
            console.log("err");
          }else{
            console.log("data"+data);
          }
        });
        
        /*
        * fin0dUser(1).then(function(data){
          console.log("test");
        }).catch(function(err){
          console.log("err");
        });
        *
        * */
        
        
          /*
          * .fin0dUser(1,function (err,data) {
            console.log("test");
						if(err){
						  console.log("err");
						}else{
						  console.log("data"+data);
						}
          });
          * */
          
          
          /*.then(data => {
          	return "mydata test";
          })
          .catch(err => {
            return "err";
          });*/
        
			}
		},`

**Comment by Erchoc** [comment]
这框架支持在moleculer中使用吗？？

**Comment by p412726700** [comment]
如果expressjs里面用没问题的话 应该组件本身是正常的 现在是换成 moleculer 就不行了么？你把配置发我看下
