### ISSUE TITLE
你好，请教一下，请问Node请求java后端数据，数据超过1700行时数据获取不到是什么情况？body对数据大小有限制吗？

### ISSUE THREAD

**Issue by dpc761218914** [p412726700/node-zookeeper-dubbo#73]
我看了你的代码 node-zookeeper-dubbo/libs/encode.js中
const DEFAULT_LEN  = 8388608; // 8 * 1024 * 1024 default body max length
最大限制为1M吗？  但是1700行应该也就60kb左右呢？？

**Comment by eztlvit** [comment]
我也遇到这问题了

**Comment by dpc761218914** [comment]
作者建议先降低版本，2.X的没问题，等大神后期优化吧。

**Comment by p412726700** [comment]
Fixed with commit a20cd528a07b32195233ac109d9d0d139c139915
