### ISSUE TITLE
socket.js中this.chunks.length报错

### ISSUE THREAD

**Issue by yaphetszmn** [p412726700/node-zookeeper-dubbo#77]
node_modules/_node-zookeeper-dubbo@3.0.9@node-zookeeper-dubbo/libs/socket.js:108:20)

socket本身已经获取到zookeeper上的dubbo服务
![image](https://user-images.githubusercontent.com/37991688/45252721-34f50180-b38e-11e8-8a92-2edd06b13bcb.png)
但是在这一步报错，其中 this.chunks 为undefined
![222](https://user-images.githubusercontent.com/37991688/45252789-5b676c80-b38f-11e8-97af-52e29ee60a96.png)

node版本  8.10.0 
dubbo  2.5.3
"node-zookeeper-dubbo": "^3.0.9"

**Comment by p412726700** [comment]
应该是可以了 再试下看

**Comment by yaphetszmn** [comment]
可以了，解决速度很快，点个赞~
