### ISSUE TITLE
发现不能监听到所有的dubbo服务

### ISSUE THREAD

**Issue by Garyhuub** [p412726700/node-zookeeper-dubbo#82]
this.client.once('connected', function () {
    self._applyServices();
    self._consumer();
  });

**Comment by p412726700** [comment]
哪些没监听到？一般只要提供了version和group就可以了

**Comment by dpc761218914** [comment]
之前好像不用配置version和group也行，如果数量多了的话，是不是需要配置呢？

**Comment by dpc761218914** [comment]
@p412726700  另外，请教一下，一个controller如果需要调用多个java类，是在同一个controller定义多个dubbo服务吗？
像这样：

> 
var nzd_config_test = require("../nzd_services/userTeacherServices_opt.js");
const nzd=require('node-zookeeper-dubbo');
const opt=nzd_config_test.userTeacherServices_opt;
//为opt赋值
opt.java = require('js-to-java');
//定义dubbo对象
var Dubbo=new nzd(opt);

**Comment by p412726700** [comment]
version 和 group 共同确定了能找到哪些服务，所以需要知道你需要的服务里面这两个字段的值，如果没有的话就不填。
一个controller调用多个java类的话，等同于配置多个不同的interface，就是说dependencies这个属性多配置几个就行了，看下reademe里面的范例。
