### ISSUE TITLE
请教一下，请定义一个dubbo的连接数量有限制吗？可以定义一个dubbo连接多个java服务吗？

### ISSUE THREAD

**Issue by dpc761218914** [p412726700/node-zookeeper-dubbo#83]
像如下代码可以吗？：

` //引入nzd配置
var nzd_config = require("../../config/nzd_config.js");
var userServices_opt={
    application:{name:nzd_config.application},
    register:nzd_config.register,
    dubboVer:nzd_config.dubboVer,
    root:nzd_config.root,
    dependencies:{
        IUserService:{
            interface:'com.jzy.edu.exam.service.AreasService',
            timeout:6000,
            version:'v1.0.0',
            group:'kjb',
            methodSignature: {
                selectTest:(id)=>[{'$class': 'java.lang.Integer','$' :id}],
            }
        },
  IUserService2:{
            interface:'com.jzy.edu.exam.service.AreasService2',
            timeout:6000,
            version:'v1.0.0',
            group:'kjb',
            methodSignature: {
                selectTest:(id)=>[{'$class': 'java.lang.Integer','$' :id}],
            }
        },
    }
};

exports.userServices_opt=userServices_opt;
`

https://github.com/dpc761218914/egg-nzd-demo/blob/master/app/nzd_services/userServices_opt.js

**Comment by p412726700** [comment]
完全可以的 另外能否把代码格式化一下 这样看着太伤眼睛了 😂
