### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by yangchongduo** [p412726700/node-zookeeper-dubbo#85]
![image](https://user-images.githubusercontent.com/19145102/47250446-9612f900-d453-11e8-8b06-350bff77ef52.png)

**Comment by dpc761218914** [comment]
你的zookeeper没连上。多改各种参数试一下，最好配合写zk的人一起调试。 我的用egg写的可以连的。https://github.com/dpc761218914/egg-nzd-demo

**Comment by p412726700** [comment]
readme上的demo不能直接复制用 你的改成你自己的zookeeper地址和service服务

**Comment by yangchongduo** [comment]
ok
