### ISSUE TITLE
请教一下，关于使用node-zookeeper-dubbo进行负载均衡的思路？使用node-zookeeper-dubbo进行负载的机制是怎样的呢？

### ISSUE THREAD

**Issue by dpc761218914** [p412726700/node-zookeeper-dubbo#86]
抱歉，对java同事写的dubbo和zookeeper理解的不太透彻。
请问是在（register:'www.cctv.com:2181',）配置多个zookeeper的连接地址吗？ node-zookeeper-dubbo是通过什么机制去选取服务的呢？
可以这样理解吗？
其实dubbo是多个服务，可以部署在不同服务器上，然后都统一在zookeeper上注册，然后Node.js工程作为消费者连接zookeeper调用dubbo服务。
如果这样的话，是不是dubbo（可部署多个服务器）+zookeeper（单个服务器，好像也可以部署多个节点）+node工程（可部署多个服务器）

**Comment by dpc761218914** [comment]
`const opt={
  application:{name:'fxxk'},
  register:'www.cctv.com:2181',
  dubboVer:'2.5.3.6',
  root:'dubbo',
  dependencies:{
    Foo:{
      interface:'com.service.Foo',
      version:'LATEST',
      timeout:6000,
      group:'isis',
      methodSignature: {
        findById : (id) => [ {'$class': 'java.lang.Long', '$': id} ],
        findByName : (name) => (java) => [ java.String(name) ],
      }
    },
    Bar:{
      interface:'com.service.Bar',
      version:'LATEST',
      timeout:6000,
      group:'gcd'
    }
  }
}`
如果 register:'www.cctv.com:2181',可以连接多个zookeeper，那么node-zookeeper-dubbo通过什么算法选择性能最好的zookeeper进行连接呢？

**Comment by MecDog** [comment]
+1 我也想知道

**Comment by p412726700** [comment]
关于多个zookeeper地址的话 负载均衡是由这个库 [node-zookeeper-client](https://github.com/alexguan/node-zookeeper-client) 做的 具体实现方式可以看下该库源码 

关于找到多个相同service的话 2.x版本是采用随机方法 目前3.0版本暂时没有做

**Comment by dpc761218914** [comment]
那配置多个zookeeper的话，就配置多个地址就可以了吧

**Comment by p412726700** [comment]
是的 配置多个地址就行
