### ISSUE TITLE
长连接断线不会重连

### ISSUE THREAD

**Issue by tonmy2012** [p412726700/node-zookeeper-dubbo#90]
复现方法：
在正常使用时网卡断开网络连接。

断开后连接不上，网络连接后不会自动重连
server error:' Error: This socket is closed

能否支持重连，默认5秒钟重连一次。
支持参数配置重连时间

**Comment by tonmy2012** [comment]
@p412726700 help

**Comment by p412726700** [comment]
正常是可以重连的啊 你打日志断点调试一下 另外你说的断开连接是对方断开还是nodejs这边断开？

**Comment by tonmy2012** [comment]
nodejs 这边网卡断开，然后操作有调用dubbo的方法。这时候会提示socket 断开。然后网卡再接上。
网络恢复后不会重新连接。一直保持socket断开状态。

**Comment by p412726700** [comment]
那还是先用2.x版本吧... 我回头修复下
