### ISSUE TITLE
长连接导致dubbo 服务端频繁输出日志

### ISSUE THREAD

**Issue by tonmy2012** [p412726700/node-zookeeper-dubbo#92]
com.alibaba.dubbo.remoting.exchange.support.header.HeartbeatHandler -  [DUBBO] Received heartbeat from remote channel /172.10.0.15:40642, cause: The channel has no data-transmission exceeds a heartbeat period: 60000ms, dubbo version: 2.6.0, current host: 127.0.0.1

输出日志太频繁 10几分钟输出了2G的日志文件

**Comment by tonmy2012** [comment]
正常使用的时候不会，估计是断线或其他原因导致。

**Comment by p412726700** [comment]
恩 应该重连问题 先回到2.x版本吧 我抽空彻底修复下这个问题
