### ISSUE TITLE
dubbox(2.8.4)异常：

### ISSUE THREAD

**Issue by liyimpc** [p412726700/node-zookeeper-dubbo#95]
![image](https://user-images.githubusercontent.com/12293187/49775582-9e8cff00-fd33-11e8-8b3b-b8d3766b88e9.png
连接成功，但是调用接口的时候，入参类型是long，我的代码写法如下：
```
          methodSignature: { // optional
                getUserLocationByIp : (ip) => [ java('long', ip) ],
          }
```
实际传入的值是：236853492，
却抛出` hessian readInt error, unexpect code: 0x31`异常，看样子是hession反序列化有问题，请问有办法解决吗？

**Comment by p412726700** [comment]
你试试传入 字符串类型的 "236853492"
